modLoader="javafml"
license="MIT License https://github.com/McJtyMods/LostCities/blob/1.16/LICENCE"
loaderVersion="[40,)"
issueTrackerURL="http://github.com/McJtyMods/LostCities/issues"
displayURL="http://github.com/McJtyMods/LostCities/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="lostcities"
version="${file.jarVersion}"
displayName="LostCities"
#updateJSONURL="http://myurl.me/" #optional
description='''
Generate cities all over the world
'''
[[dependencies.lostcities]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.50,)"
    ordering="NONE"
    side="BOTH"
